### ISSUE TITLE
HelloWorld not working.

### ISSUE THREAD

**Issue by rygo6** [microsoft/mixed-reality-extension-unity#83]
I've encountered a series of issues following the "How to build and run Hello World in the Unity3D editor" instructions.

Your instructions mention a 'RunHelloWorld.bat' in the getting started section. However this bat file seems to be missing from both master and red branches.

I then tried to run the 'buildMREUnityRuntimeDLL.bat' file directly. However this encounters issues when you have both VS2017 and VS2019 installed. As this section in the .bat file:
```
for /f "usebackq tokens=*" %%i in (`"%~dp0tools\vswhere" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set VSInstallDir=%%i
)
```
Sets the VSInstallDir environment variable to the VS2019 directory and then MSBuild does not work.

Deleting that section from the .bat will get a build going. But it fails with these errors:
```
BUILD FAILED: Failed Visual Studio build
Make sure you have Visual Studio 2017, and Visual Studio's Unity Tools installed
```

I can see further up in the log it is looking all around for UnityEngine.dll, then if I open MREUnityRuntime.sln I can see that it is missing the path to the UnityEngine.dll

I presume I shouldn't be following these issues down the rabbit hole of debugging. Is there something that should be done differently to get this to work?

**Comment by stevenvergenz** [comment]
Sorry, those instructions are out of date, and that script is inoperable. We don't have much of a focus on documentation since it's still in preview and things change so fast. The general flow you should follow is:

* Build the MREUnityRuntime project. This will generate DLLs and copy them into the testbed assets folder
* Open the testbed Unity project, let it compile, and run in the Standalone scene (which defaults to ws://localhost:3901)
* Observe your locally hosted app running

**Comment by sorenhan** [comment]
I removed the RunHelloWorld.bat reference from documentation - it was unnecessary.

**Comment by stevenvergenz** [comment]
@rygo6 Is this issue solved to your satisfaction? You got the Unity project building successfully?

**Comment by sorenhan** [comment]
I fixed BuildMREUnityRuntimeDLL.bat to work if you have VS2017 and 2019 installed. This should be fixed
